import { Room, Testimonial, Amenity, NavItem, Attraction } from './types';
import { Wifi, Utensils, Droplets, Car, Dumbbell, Calendar, MapPin, Coffee } from 'lucide-react';

export const NAV_ITEMS: NavItem[] = [
  { label: 'Home', href: '#hero' },
  { label: 'Rooms', href: '#rooms' },
  { label: 'Dining', href: '#dining' },
  { label: 'Events', href: '#events' },
  { label: 'Experiences', href: '#location' },
  { label: 'Blogs', href: '#blogs' },
  { label: 'Contact', href: '#contact' },
];

export const ROOMS: Room[] = [
  // Batian Wing (Modern Luxury)
  {
    id: 'b1',
    name: 'Premier Grand Suite (Presidential)',
    category: 'Batian Wing',
    description: 'Experience luxury and grandeur at its finest. This opulent two-bedroom suite features a kitchen, an impeccable lounge with a dining area, and a breakfast counter. Perfect for dignitaries, VIPs, and families seeking the ultimate in comfort and privacy.',
    price: 850,
    priceKsh: 110000,
    size: '120 sqm',
    guests: 4,
    amenities: [
      'Master Bedroom with King Size Bed',
      'Guest Bedroom with Queen Bed',
      'Private Jacuzzi Whirlpool Bath',
      'Separate Rain Shower Cubicle',
      'Guest Powder Room',
      'Full Kitchen (Fridge, Oven, Microwave)',
      '6-Seater Dining Table',
      'Breakfast Counter with Bar Stools',
      'Opulent Lounge with Leather Seating',
      'Two 65" 4K Smart TVs with Netflix',
      'Dedicated Workspace with Ergonomic Chair',
      'High-Speed Wi-Fi & LAN Ports',
      'Walk-in Wardrobe',
      'Three Private Balconies',
      'Electronic Laptop Safe',
      'Espresso Machine & Tea Station',
      'Premium Toiletries & Vanity Kit'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&q=80&w=800',
    featured: true,
  },
  {
    id: 'b2',
    name: 'Premier Family Suite',
    category: 'Batian Wing',
    description: 'A haven of style and space with two bedrooms, a kitchen, and a sophisticated lounge area. Designed for families and friends seeking a shared, luxurious apartment-style living with modern conveniences.',
    price: 550,
    priceKsh: 72000,
    size: '90 sqm',
    guests: 4,
    amenities: [
      'Master Bedroom (King Bed)',
      'Second Bedroom (Twin Beds)',
      'Two Modern Bathrooms (Bathtub & Shower)',
      'Kitchenette with Microwave & Large Fridge',
      'Spacious Open-Plan Lounge',
      '4-Seater Dining Area',
      '55" Smart TV with Streaming Apps',
      'Private Balcony with Seating',
      'Work Desk with Lamp',
      'High-Speed Wi-Fi',
      'Tea & Coffee Making Facilities',
      'Intercom System',
      'Daily Housekeeping',
      'Iron & Ironing Board',
      'Soundproof Windows'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1522771753035-4a53c9d1314d?auto=format&fit=crop&q=80&w=800',
    featured: false,
  },
  {
    id: 'b3',
    name: 'Junior Executive Suite',
    category: 'Batian Wing',
    description: 'A perfect haven for business travelers and couples. This suite offers an inviting ambiance, blending elegance and convenience for a peaceful urban retreat with dedicated workspace.',
    price: 350,
    priceKsh: 46000,
    size: '55 sqm',
    guests: 2,
    amenities: [
      'King Size Bed with Premium Linens',
      'Dedicated Executive Work Desk',
      'Ergonomic Office Chair',
      'Comfortable Lounge Area with Sofa',
      'City View Balcony',
      'Walk-in Glass Rain Shower',
      '43" Smart TV with Satellite Channels',
      'High-Speed Wi-Fi',
      'International Power Sockets',
      'Mini Fridge',
      'Electronic Safe',
      'Coffee Maker & Kettle',
      'Individually Controlled Air Conditioning',
      'USB Charging Ports'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1590490359683-658d3d23f972?auto=format&fit=crop&q=80&w=800',
    featured: false,
  },
  {
    id: 'b4',
    name: 'Deluxe Twin Suites',
    category: 'Batian Wing',
    description: 'The ideal urban retreat for making family memories. Features separate adjacent rooms with twin beds or convertible king-size beds to ensure your family stays connected yet comfortable.',
    price: 300,
    priceKsh: 39000,
    size: '50 sqm',
    guests: 4,
    amenities: [
      'Two Twin Beds / Convertible King',
      'Interconnecting Room Option',
      'Cozy Sitting Area by Window',
      'Large Wardrobe with Full Mirror',
      'En-suite Bathroom with Shower',
      'Flat Screen TV with Satellite Channels',
      'High-Speed Wi-Fi',
      'Study Desk & Chair',
      'Soundproofing for Quiet Sleep',
      '24-Hour Room Service Menu',
      'Tea/Coffee Station',
      'Bedside Reading Lights',
      'Luggage Rack'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&q=80&w=800',
    featured: false,
  },
  {
    id: 'b5',
    name: 'Deluxe Room Single',
    category: 'Batian Wing',
    description: 'The perfect blend of convenience & elegance for business and leisure travelers alike. Rest and recharge in this luxurious accommodation designed to make you feel right at home.',
    price: 200,
    priceKsh: 26000,
    size: '35 sqm',
    guests: 1,
    amenities: [
      'Queen Size Bed',
      'Modern En-suite Bathroom',
      'Glass Shower Cubicle',
      'Compact Work Desk',
      'Comfortable Armchair',
      'Electric Kettle & Tea Set',
      '32" Satellite TV',
      'High-Speed Wi-Fi',
      'Complimentary Bottled Water',
      'Telephone',
      'Premium Toiletries',
      'Blackout Curtains'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&q=80&w=800',
    featured: false,
  },
  {
    id: 'b6',
    name: 'Honeymoon Room',
    category: 'Batian Wing',
    description: 'Escape to our city oasis, where love and luxury intertwine. Our honeymoon room provides the ultimate comfort and sophistication, as we cater to your every desire. Indulge in the romantic allure where memories are etched forever. Relax in the plush embrace of our lavish accommodations, where every detail is thoughtfully crafted to ignite the flames of passion. From this room you will experience the epitome of comfort and luxury, where every moment is a delightful escape.',
    price: 400,
    priceKsh: 52000,
    size: '45 sqm',
    guests: 2,
    amenities: [
      'King Size Bed with Egyptian Cotton Linens',
      'Romantic Turndown Service (Petals/Chocolates)',
      'Luxury Bathtub for Two with Bath Salts',
      'Separate Walk-in Rain Shower',
      'Complimentary Champagne on Arrival',
      'Ambient Mood Lighting System',
      'Private Balcony with City Views',
      '55" 4K Smart TV with Streaming',
      'High-Speed Fiber Wi-Fi',
      'Plush Bathrobes & Velour Slippers',
      'Fresh Fruit Basket',
      'Late Check-out (Subject to Availability)',
      'In-Room Breakfast Options',
      'Soundproof Windows',
      'Climate Control'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&q=80&w=800',
    featured: true,
  },
  // Lenana Wing (Vintage/Classic)
  {
    id: 'l1',
    name: 'Deluxe Room Single',
    category: 'Lenana Wing',
    description: 'Embraces vintage elegance with signature shades of blue and classic chairs. Decked with symmetrical palm trees right outside the entrance, offering a serene connection to nature.',
    price: 150,
    priceKsh: 19500,
    size: '30 sqm',
    guests: 1,
    amenities: [
      'Vintage-Style Decor',
      'Direct Garden/Patio Access',
      'Antique Wooden Work Desk',
      'Classic Wingback Armchair',
      'En-suite Bathroom with Hot Shower',
      'Traditional Mosquito Netting',
      'Ceiling Fan',
      'Telephone',
      'Complimentary Bottled Water',
      'Wi-Fi Access',
      'Satellite TV',
      'Garden Views'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1616594039964-40891a909d99?auto=format&fit=crop&q=80&w=800',
    featured: false,
  },
  {
    id: 'l2',
    name: 'Standard Twin Room',
    category: 'Lenana Wing',
    description: 'Ideal for family and friends who don’t mind sharing the same space. This room exudes warmth, embodying the rich heritage of our city with classic touches.',
    price: 180,
    priceKsh: 23500,
    size: '35 sqm',
    guests: 2,
    amenities: [
      'Two Comfortable Single Beds',
      'Heritage Decor & Warm Lighting',
      'Shared Seating Area',
      'Writing Desk with Lamp',
      'Private Bathroom with Shower',
      'Spacious Wardrobe',
      'Wi-Fi Access',
      'Mosquito Nets',
      'Satellite TV',
      'Large Windows with Garden View'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&q=80&w=800',
    featured: false,
  },
  {
    id: 'l3',
    name: 'Standard Single Room',
    category: 'Lenana Wing',
    description: 'Perfect for the budget traveler. Discover a well-appointed space that combines vintage charm with modern comfort, all decked with symmetrical palm trees.',
    price: 100,
    priceKsh: 13000,
    size: '25 sqm',
    guests: 1,
    amenities: [
      'Single Bed with Mosquito Net',
      'Cozy Compact Layout',
      'Garden Views',
      'Small Writing Table',
      'En-suite Shower Room',
      'Essential Toiletries',
      'Quiet Garden Ambience',
      'Wi-Fi Access',
      'Natural Ventilation'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1629140727571-9b5c6f6267b4?auto=format&fit=crop&q=80&w=800',
    featured: false,
  },
];

export const AMENITIES: Amenity[] = [
  {
    id: '1',
    title: 'Fine Dining',
    description: 'Experience gourmet cuisine crafted by world-class chefs using local ingredients.',
    iconName: 'Utensils',
  },
  {
    id: '2',
    title: 'Luxury Spa',
    description: 'Rejuvenate your senses with our exclusive range of therapeutic treatments.',
    iconName: 'Droplets',
  },
  {
    id: '3',
    title: 'Valet Parking',
    description: 'Complimentary secure parking with 24/7 valet service for all guests.',
    iconName: 'Car',
  },
  {
    id: '4',
    title: 'Fitness Center',
    description: 'State-of-the-art equipment available 24 hours a day to keep up with your routine.',
    iconName: 'Dumbbell',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Eleanor Sterling',
    location: 'London, UK',
    rating: 5,
    comment: 'The attention to detail at Three Steers is unmatched. The blend of heritage and modern luxury created an unforgettable stay.',
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=100&h=100',
  },
  {
    id: '2',
    name: 'James Harrington',
    location: 'New York, USA',
    rating: 5,
    comment: 'Exceptional service from the moment we arrived. The Presidential Suite exceeded all expectations.',
    imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=100&h=100',
  },
  {
    id: '3',
    name: 'Sofia Martinez',
    location: 'Madrid, Spain',
    rating: 4,
    comment: 'Beautiful architecture and a wonderful spa experience. Highly recommended for a relaxing getaway.',
    imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=100&h=100',
  },
];

export const ATTRACTIONS: Attraction[] = [
  {
    id: '1',
    name: 'Ngare Ndare Forest Reserve',
    type: 'Nature',
    distance: 'Excursion',
    rating: 5.0,
  },
  {
    id: '2',
    name: 'Mt. Kenya Hiking',
    type: 'Adventure',
    distance: 'Excursion',
    rating: 5.0,
  },
  {
    id: '3',
    name: 'Lewa Wildlife Conservancy',
    type: 'Safari',
    distance: 'Excursion',
    rating: 5.0,
  },
  {
    id: '4',
    name: 'Meru National Reserve',
    type: 'Game Drive',
    distance: 'Excursion',
    rating: 4.8,
  },
  {
    id: '5',
    name: 'Cultural Tours',
    type: 'Culture',
    distance: 'Local',
    rating: 4.5,
  },
  {
    id: '6',
    name: 'Meru Museum',
    type: 'History',
    distance: 'Local',
    rating: 4.2,
  }
];