import { Room, Testimonial, Amenity, NavItem, Attraction } from './types';
import { Wifi, Utensils, Droplets, Car, Dumbbell, Calendar, MapPin, Coffee } from 'lucide-react';

export const NAV_ITEMS: NavItem[] = [
  { label: 'Home', href: '#hero' },
  { label: 'Rooms', href: '#rooms' },
  { label: 'Dining', href: '#dining' },
  { label: 'Events', href: '#events' },
  { label: 'Experiences', href: '#location' },
  { label: 'Blogs', href: '#blogs' },
  { label: 'Contact', href: '#contact' },
];

export const ROOMS: Room[] = [
  // Batian Wing
  {
    id: 'b1',
    name: 'Premier Grand Suite (Presidential)',
    category: 'Batian Wing',
    description: 'Experience luxury and grandeur at its finest. This opulent two-bedroom suite features a kitchen, an impeccable lounge with a dining area, and a breakfast counter. Perfect for dignitaries, VIPs, and families.',
    price: 850,
    size: '120 sqm',
    guests: 4,
    amenities: ['2 Bedrooms', 'Kitchen', 'Dining Area', 'Breakfast Counter', 'Lounge'],
    imageUrl: 'https://picsum.photos/id/1036/800/600',
    featured: true,
  },
  {
    id: 'b2',
    name: 'Premier Family Suite',
    category: 'Batian Wing',
    description: 'A haven of style and space with two bedrooms, a kitchen, and a sophisticated lounge area. Designed for families and friends seeking a shared, luxurious apartment-style living.',
    price: 550,
    size: '90 sqm',
    guests: 4,
    amenities: ['2 Bedrooms', 'Kitchen', 'Lounge', 'Apartment Style'],
    imageUrl: 'https://picsum.photos/id/234/800/600',
    featured: false,
  },
  {
    id: 'b3',
    name: 'Junior Executive Suite',
    category: 'Batian Wing',
    description: 'A perfect haven for business travelers and couples. This suite offers an inviting ambiance, blending elegance and convenience for a peaceful urban retreat.',
    price: 350,
    size: '55 sqm',
    guests: 2,
    amenities: ['King Bed', 'Work Desk', 'Lounge Area', 'City View'],
    imageUrl: 'https://picsum.photos/id/366/800/600',
    featured: false,
  },
  {
    id: 'b4',
    name: 'Deluxe Twin Suites',
    category: 'Batian Wing',
    description: 'The ideal urban retreat for making family memories. Features separate adjacent rooms with twin beds and king-size beds to ensure your kids are right next to you.',
    price: 300,
    size: '50 sqm',
    guests: 4,
    amenities: ['Twin Beds', 'King Bed', 'Connecting Rooms', 'Family Friendly'],
    imageUrl: 'https://picsum.photos/id/1040/800/600',
    featured: false,
  },
  {
    id: 'b5',
    name: 'Deluxe Room Single',
    category: 'Batian Wing',
    description: 'The perfect blend of convenience & elegance for business and leisure travelers alike. Rest and recharge in this luxurious accommodation designed to make you feel right at home.',
    price: 200,
    size: '35 sqm',
    guests: 1,
    amenities: ['Queen Bed', 'En-suite Bath', 'Work Area'],
    imageUrl: 'https://picsum.photos/id/1035/800/600',
    featured: false,
  },
  {
    id: 'b6',
    name: 'Honeymoon Room',
    category: 'Batian Wing',
    description: 'Escape to our city oasis, where love and luxury intertwine. This room provides the ultimate comfort and sophistication, crafted to ignite the flames of passion.',
    price: 400,
    size: '45 sqm',
    guests: 2,
    amenities: ['Romantic Decor', 'Luxury Bath', 'Champagne Service', 'King Bed'],
    imageUrl: 'https://picsum.photos/id/364/800/600',
    featured: true,
  },
  // Lenana Wing
  {
    id: 'l1',
    name: 'Deluxe Room Single',
    category: 'Lenana Wing',
    description: 'Embraces vintage elegance with signature shades of blue and classic chairs. Decked with symmetrical palm trees right outside the entrance.',
    price: 150,
    size: '30 sqm',
    guests: 1,
    amenities: ['Vintage Decor', 'Garden View', 'Work Desk'],
    imageUrl: 'https://picsum.photos/id/299/800/600',
    featured: false,
  },
  {
    id: 'l2',
    name: 'Standard Twin Room',
    category: 'Lenana Wing',
    description: 'Ideal for family and friends who don’t mind sharing the same space. This room exudes warmth, embodying the rich heritage of our city.',
    price: 180,
    size: '35 sqm',
    guests: 2,
    amenities: ['Twin Beds', 'Warm Ambiance', 'Heritage Style'],
    imageUrl: 'https://picsum.photos/id/403/800/600',
    featured: false,
  },
  {
    id: 'l3',
    name: 'Standard Single Room',
    category: 'Lenana Wing',
    description: 'Perfect for the budget traveler. Discover a well-appointed space that combines vintage charm with modern comfort, all decked with symmetrical palm trees.',
    price: 100,
    size: '25 sqm',
    guests: 1,
    amenities: ['Single Bed', 'Cozy Layout', 'Garden Access'],
    imageUrl: 'https://picsum.photos/id/238/800/600',
    featured: false,
  },
];

export const AMENITIES: Amenity[] = [
  {
    id: '1',
    title: 'Fine Dining',
    description: 'Experience gourmet cuisine crafted by world-class chefs using local ingredients.',
    iconName: 'Utensils',
  },
  {
    id: '2',
    title: 'Luxury Spa',
    description: 'Rejuvenate your senses with our exclusive range of therapeutic treatments.',
    iconName: 'Droplets',
  },
  {
    id: '3',
    title: 'Valet Parking',
    description: 'Complimentary secure parking with 24/7 valet service for all guests.',
    iconName: 'Car',
  },
  {
    id: '4',
    title: 'Fitness Center',
    description: 'State-of-the-art equipment available 24 hours a day to keep up with your routine.',
    iconName: 'Dumbbell',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Eleanor Sterling',
    location: 'London, UK',
    rating: 5,
    comment: 'The attention to detail at Three Steers is unmatched. The blend of heritage and modern luxury created an unforgettable stay.',
    imageUrl: 'https://picsum.photos/id/64/100/100',
  },
  {
    id: '2',
    name: 'James Harrington',
    location: 'New York, USA',
    rating: 5,
    comment: 'Exceptional service from the moment we arrived. The Presidential Suite exceeded all expectations.',
    imageUrl: 'https://picsum.photos/id/91/100/100',
  },
  {
    id: '3',
    name: 'Sofia Martinez',
    location: 'Madrid, Spain',
    rating: 4,
    comment: 'Beautiful architecture and a wonderful spa experience. Highly recommended for a relaxing getaway.',
    imageUrl: 'https://picsum.photos/id/65/100/100',
  },
];

export const ATTRACTIONS: Attraction[] = [
  {
    id: '1',
    name: 'Ngare Ndare Forest Reserve',
    type: 'Nature',
    distance: 'Excursion',
    rating: 5.0,
  },
  {
    id: '2',
    name: 'Mt. Kenya Hiking',
    type: 'Adventure',
    distance: 'Excursion',
    rating: 5.0,
  },
  {
    id: '3',
    name: 'Lewa Wildlife Conservancy',
    type: 'Safari',
    distance: 'Excursion',
    rating: 5.0,
  },
  {
    id: '4',
    name: 'Meru National Reserve',
    type: 'Game Drive',
    distance: 'Excursion',
    rating: 4.8,
  },
  {
    id: '5',
    name: 'Cultural Tours',
    type: 'Culture',
    distance: 'Local',
    rating: 4.5,
  },
  {
    id: '6',
    name: 'Meru Museum',
    type: 'History',
    distance: 'Local',
    rating: 4.2,
  }
];